# Generated by Django 4.2.5 on 2023-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guest_score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(),
        ),
    ]
