# Generated by Django 4.2.5 on 2023-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0004_alter_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='guest_wo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='home_wo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
