# Generated by Django 4.2.5 on 2023-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0005_match_guest_wo_match_home_wo_match_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guest_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
