# Generated by Django 4.2.5 on 2023-09-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0006_alter_match_guest_score_alter_match_home_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='guest_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='home_check',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('championship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ_name', to='gombfoci.championship')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_name', to='gombfoci.season')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='league_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='league_name', to='gombfoci.league'),
        ),
    ]
