# Generated by Django 4.2.5 on 2023-09-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0007_championship_match_guest_check_match_home_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_name', to='gombfoci.league'),
        ),
    ]
