# Generated by Django 4.2.5 on 2023-09-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0008_alter_match_league_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('founded', models.PositiveIntegerField(default=2000)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.AddField(
            model_name='team',
            name='league_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='league_name_id', to='gombfoci.league'),
        ),
        migrations.AddField(
            model_name='team',
            name='club_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='club_name', to='gombfoci.club'),
        ),
    ]
