# Generated by Django 4.2.5 on 2023-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0009_club_remove_team_points_team_league_id_team_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
