# Generated by Django 4.2.5 on 2023-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gombfoci', '0010_alter_championship_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
